oc20_elem_refs:
  - -8.107700490621648e-19
  - -3.3423202090809947
  - 0.03262097999999956
  - -1.6989051778718063
  - -3.4210216186289424
  - -6.070353132916837
  - -8.288281713720627
  - -8.36148717655228
  - -4.98866748307435
  - -0.85645180369079
  - 0.026739969999999554
  - -1.5654299767238529
  - -1.5194316996946489
  - -3.6311822846907993
  - -5.349390558833624
  - -5.288544638550745
  - -4.599072279532397
  - -3.0525373442095396
  - -0.006726819999999667
  - -1.5562093965468387
  - -2.457299507693322
  - -6.79275316521327
  - -7.792664635315558
  - -8.37696778260591
  - -8.422463880840017
  - -7.8173554603019815
  - -7.1067097201672365
  - -6.181547708808164
  - -4.848432059465626
  - -2.941656827655197
  - -0.6686379771348783
  - -2.58751856361606
  - -4.08386263075538
  - -4.490058529001618
  - -3.8140545293614068
  - -1.2338017152383036
  - -0.002583539999999667
  - -1.3747485579035916
  - -2.3565098629818695
  - -7.0634073482512205
  - -8.573538954429536
  - -9.555066216092646
  - -9.828482585121902
  - -9.262079948501807
  - -8.340023277228887
  - -6.727818303339194
  - -4.759635392112392
  - -1.9049051327348479
  - -0.22723170433378648
  - -2.0774508137450445
  - -3.396769362301625
  - -3.6467407084485877
  - -3.0314438945821616
  - -1.1766727949138396
  - 0.01091345
  - -1.5642012892838286
  - -1.8805128486950369
  - -4.666756901848997
  - -6.070958335854221
  - -5.235785587061488
  - -7.287949777373623
  - -10.70940462
  - -8.85923266632015
  - -2.1196438637624277
  - -12.989245428364214
  - -11.986218611906072
  - -10.140198214920053
  - -9.76169966193089
  - -8.39407967598287
  - -6.832065652554835
  - -1.604197471772876
  - -4.501324038276187
  - -9.961151723945559
  - -11.143939461242013
  - -11.649703992946236
  - -11.05299323060887
  - -10.093296893820078
  - -8.157382708515758
  - -5.689546736486195
  - -2.6414176904215374
  - 0.31655256934396814
  - -1.8045599792439964
  - -3.0299508299310354
  - -3.311473974726504
  - -0.10039175
  - -0.06069209
  - 0.01790437
  - -0.04694024
  - -1.6445780353456858
  - -4.268199690442443
  - -6.827226523069828
  - -7.113301896475604
  - -10.498991496787738
  - -10.487168959713696
  - -12.007219251410449
  - -14.093465752378457
  - -16.9583162073172
  - -3.212923593441274
  - -16.507424142627386
  - -1.378447864282869
odac_elem_refs:
  - 8.558312926061463e-17
  - -4.0300954232673645
  - -0.00011834999827904329
  - -4.320709440740138
  - -7.199442939952119
  - -7.289341453261438
  - -8.83807290997521
  - -8.00500532211806
  - -6.939655133318947
  - -4.4309990294457045
  - -0.01137327000001954
  - -3.816984168730863
  - -5.759858132479971
  - -9.660398373996616
  - -7.34027690735354
  - -7.0568410467783185
  - -4.276376543901737
  - -2.894451035750203
  - -0.020145359999993784
  - -1.081430529407329
  - -7.438949739086279
  - -10.004726923474234
  - -13.445920857812162
  - -11.663228306387943
  - -10.25612815712514
  - -10.456762979259278
  - -8.527552627470055
  - -6.9153012560050175
  - -4.882665255635376
  - -3.145677594049243
  - -2.3075672287334497
  - -5.421007079793103
  - -4.649846092686984
  - -3.6461633453793696
  - -3.7029966720400562
  - -0.9371144382880114
  - -0.022399909999998666
  - -0.9796285351916173
  - -7.178500722428577
  - -13.887922229070163
  - -15.507336305694764
  - -6.992305978954096
  - -11.47541986946262
  - -10.333675276945756
  - -9.309140180493962
  - -8.39377113813413
  - -6.402376345586537
  - -1.8020730129312343
  - -0.733097264337675
  - -2.755205196471708
  - -3.072151468818221
  - -2.7722090102164705
  - -2.412220531384588
  - -2.7373651675848656
  - -0.01118184000000333
  - -2.158009724808714
  - -7.973791072143521
  - -11.865103987231066
  - -12.561365553559591
  - -13.001284722213727
  - -14.28992348946669
  - -5.45866275
  - -17.978561388575834
  - -15.07821222301671
  - -21.05047201316279
  - -19.04576122229131
  - -16.642017871853536
  - -15.282169594519123
  - -13.20681657534128
  - -12.689583459027556
  - -1.642632548514394
  - -11.253821176185971
  - -17.02169635618025
  - -11.56373101119702
  - -14.666899530085809
  - -13.952497327890661
  - -11.063759859478331
  - -8.216557930039393
  - -5.767156510069714
  - -3.611933379385488
  - -0.8348394642814021
  - -2.1088239113709677
  - -2.684610226902376
  - -5.007623195721049
  - -0.66500178
  - -0.22643927
  - -0.00728197
  - -0.11208472
  - -1.6554974353456857
  - -4.425879850442443
  - -16.10447892228396
  - -7.616955426475604
  - -15.54729271017484
  - -18.08976889095316
  - -11.16593345141045
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
omat_elem_refs:
  - 1.0553550374387596e-19
  - -2.975857957435302
  - 0.11322146060509768
  - -2.0984139889834994
  - -3.0979414945246715
  - -6.111110844700471
  - -7.423438653595413
  - -7.913379964536655
  - -7.160353623328677
  - -4.8255267098953825
  - 3.126853223112276
  - -1.3535329407051142
  - -1.3470892893936814
  - -3.65645562423946
  - -5.185940950937475
  - -5.292289841614557
  - -5.36133914647933
  - -3.1501708199235576
  - 3.91718565717847
  - -0.8086478961223098
  - -2.2574785101939474
  - -6.544008236888187
  - -7.861637107244404
  - -8.261157447456394
  - -7.997938077519461
  - -7.886356405087074
  - -6.987131132971218
  - -6.053612237423413
  - -5.015915667280881
  - -3.0042897097320127
  - -0.9075621168897914
  - -2.8832178511114046
  - -4.373946175852582
  - -4.6246581526253685
  - -4.511903579808875
  - -2.5864472604050697
  - 1.980279624402816
  - -1.1407814791878965
  - -2.0786321810132913
  - -6.519671594723293
  - -8.433774447186913
  - -9.36037380584141
  - -9.281368386988547
  - -9.079005601284361
  - -8.220188771206146
  - -7.139871125140867
  - -5.42477801713693
  - -2.1426509638204334
  - -0.38027328971420304
  - -2.27787713669116
  - -3.7329439956642574
  - -3.929279858106735
  - -3.7444861070469986
  - -2.0836729680140174
  - 7.35520262476505
  - -1.2474269337031731
  - -2.3356332099837758
  - -5.2181003471884875
  - -6.517410694399645
  - -5.112624842724747
  - -5.071342220762391
  - -5.1519737569706265
  - -4.94134303822203
  - -10.027911945652539
  - -13.836756019224701
  - -4.822419731499212
  - -4.753430114940535
  - -4.694973327016655
  - -4.697313447310114
  - -4.574747740166432
  - -5.603464079421395
  - -4.639013196683929
  - -9.71305121886213
  - -10.683240604554427
  - -10.704946079049277
  - -10.256563708648644
  - -9.43648262051915
  - -8.280000159708946
  - -6.312589813965881
  - -3.1531089594492148
  - 0.16158403822102574
  - -1.937295162353668
  - -3.1608998939014725
  - -3.664814078908834
  - 7.771561172376096e-15
  - -1.1379786002407855e-15
  - -1.0658141036401503e-14
  - -1.3211653993039363e-14
  - -1.647918875345686
  - -4.755612086891053
  - -8.150330106820517
  - -10.599096141420477
  - -12.668578989143285
  - -13.6627908340018
  - -14.443264671351098
  - -2.943452582378457
  - -4.000608087317199
  - -3.212923593441274
  - -2.031396852627386
  - -1.378447864282869
omol_elem_refs:
  - -1.156629225040026e-15
  - -16.001316695716987
  - -82.01087430838089
  - -201.82956857988097
  - -392.37382000025474
  - -678.7577802660586
  - -1037.0951083942327
  - -1490.3891424843594
  - -2047.6980007878883
  - -2717.4000859159146
  - -3511.9177958942937
  - -4412.34353756339
  - -5442.048852490966
  - -6589.238285511481
  - -7880.842380936224
  - -9290.366602061926
  - -10834.813633824462
  - -12522.319387833275
  - -14357.418706857397
  - -16323.294755148576
  - -18435.01990024982
  - -20696.697448280793
  - -23112.143048514245
  - -25682.83219323889
  - -28416.863013932467
  - -31314.828666123234
  - -34381.61625929281
  - -37622.0970301371
  - -41038.77074996302
  - -44633.87178654121
  - -48413.89305602666
  - -52371.64723336532
  - -56519.32612658109
  - -60840.896102839535
  - -65348.22274342182
  - -70042.31301581895
  - -74932.45491967947
  - -653.3100819462285
  - -831.4256441321643
  - -1038.3067074649807
  - -1270.5802453884555
  - -1546.2069619314702
  - -1844.151869397674
  - -2185.315025224292
  - -2572.1188857512716
  - -2998.6928887542217
  - -3471.81081638118
  - -3993.2282048969632
  - -4560.650406219408
  - -5163.202864090282
  - -5822.573487382639
  - -6540.2964462130585
  - -7296.665490756577
  - -8099.4071751019965
  - -8964.710394463762
  - -546.2179067379832
  - -689.6398798417333
  - -850.4805849513325
  - -12917.08295504127
  - -14058.981210064643
  - -15267.41531050162
  - -16544.445729634244
  - -17894.054958218647
  - -19321.404884189622
  - -20822.18831205945
  - -22422.829984851378
  - -24073.462031913972
  - -25787.271913480094
  - -27608.607061532348
  - -29517.834852414315
  - -31519.198453963163
  - -33610.154761607024
  - -1293.3349595217703
  - -1542.107003487292
  - -1813.074616850505
  - -2116.0691118518926
  - -2451.555058191304
  - -2827.017838069772
  - -3237.345589780805
  - -3682.7850194399866
  - -4168.118509910375
  - -4683.015643495902
  - -5238.7226964026495
  - -5832.098572286902
  - -6469.07296
  - -7140.86455
  - -7854.60638
  - 0.0
  - -1.6479188753456857
  - -4.207893480442443
  - -6.239290333069828
  - -5.835083816475604
  - -5.524155726787739
  - -4.817312409713694
  - -3.57567303141045
  - -2.943452582378457
  - -4.000608087317199
  - -3.212923593441274
  - -2.031396852627386
  - -1.378447864282869
omc_elem_refs:
  - 6.7898932991543685e-18
  - -3.816662236936585
  - 4.511999999911182e-05
  - -1.683299757871802
  - -3.3964485586289426
  - -8.587561962067513
  - -8.943918141458088
  - -8.139969024831354
  - -6.65305882736016
  - -4.058854953790034
  - -0.012186309999999779
  - -1.1506616780481838
  - -1.5251750596946474
  - -3.4874141259986713
  - -6.303314731491455
  - -6.441319720221468
  - -3.8859751081745753
  - -2.393234172514966
  - -0.02374602
  - -0.9754111194073334
  - -1.8690819365126554
  - -5.692835649618885
  - -6.153133987412009
  - -6.13857547780315
  - -4.610583186836356
  - -3.2503473271021104
  - -4.509275862176933
  - -4.562550308844033
  - -4.556969032416842
  - -3.5346165887643757
  - -1.3626797199181055
  - -2.8803538371551864
  - -3.944241952129529
  - -3.230320991019308
  - -2.445121814273525
  - -1.7244194257912382
  - -0.02244872
  - -0.8915059410062303
  - -1.7284592536269965
  - -6.3497596195315085
  - -7.656003450319926
  - -8.288702968040173
  - -7.091689275656506
  - -7.233290816945754
  - -7.225509665330243
  - -6.731652858881768
  - -5.378878635806816
  - -2.9912323018106113
  - -1.172969879199352
  - -2.5897074364717083
  - -3.2211210669831303
  - -2.8326633938572368
  - -2.125174907679625
  - -1.0914516738792495
  - -0.01246646
  - -0.8397959987040563
  - -1.888491988695037
  - -4.727860611848997
  - -31.55427313585422
  - -3.783137037061488
  - -3.4703389273736227
  - -0.07799715
  - -2.2203563563201505
  - -1.8381837837624277
  - -4.194394848364214
  - -4.02859174190607
  - -3.0782122549200537
  - -3.193082181930891
  - -3.3495063759828696
  - -2.4871334125548357
  - -1.683862191772876
  - -4.503357448276187
  - -9.101293228466455
  - -10.32412652119702
  - -10.49974947747911
  - -9.083295463946921
  - -8.612103319478331
  - -7.078580720039394
  - -6.046838451064476
  - -3.852155393952696
  - -0.6469247325716065
  - -1.9521840097417271
  - -2.1136677052731354
  - -2.2733088532110335
  - -0.09501217
  - -0.0574478
  - -0.00599173
  - -0.04134751
  - -1.6561871753456856
  - -4.294940400442442
  - -6.735854583069828
  - -11.077415196475604
  - -7.849581786787739
  - -9.154974009713694
  - -9.53997979141045
  - -2.943452582378457
  - -4.000608087317199
  - -3.2513487834412738
  - -2.031396852627386
  - -1.378447864282869
