name: tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: 32-core-ubuntu
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        python_version: ['3.10', '3.12']

    steps:
      # Check out the PR code (not the base branch)
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Optional: get full history if needed
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python_version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install core dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install packages/fairchem-core[dev]
          pip install packages/fairchem-data-oc[dev]
          pip install packages/fairchem-demo-ocpapi[dev]
          pip install -r tests/requirements.txt # pin test packages

      - name: Install additional dependencies
        run: |
          wget https://github.com/m3g/packmol/archive/refs/tags/v20.15.0.tar.gz
          tar -xzvf v20.15.0.tar.gz
          cd packmol-20.15.0
          ./configure
          make
          echo "$(readlink -f .)" >> $GITHUB_PATH

      - name: Test core with pytest
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pytest tests --durations=0 -vv --ignore=tests/demo/ocpapi/tests/integration/ --ignore=tests/applications/ --cov-report=xml --cov=fairchem -c ./packages/fairchem-core/pyproject.toml

      - name: Core GPU tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pytest tests/core --durations=0 -vv -m gpu -c ./packages/fairchem-core/pyproject.toml -s

      - if: ${{ matrix.python_version == '3.12' }}
        name: codecov-report
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false # optional (default = false)
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)

  test_gpu:
    runs-on: 4-core-ubuntu-gpu-t4
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        python_version: ['3.12']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python_version }}

      - name: Install core dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install packages/fairchem-core[dev]
          pip install -r tests/requirements.txt # pin test packages

      - name: Core GPU tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pytest tests/core --durations=0 -vv -m gpu -c ./packages/fairchem-core/pyproject.toml
